import esbuild from "esbuild";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Disable filesystem bundling: inject empty objects for templates/personas
const systemTemplates = {};
const systemPersonas = {};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.tsx"],
	bundle: true,
	platform: "browser",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr"
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		'global': 'globalThis',
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		// Inject bundled templates into the build
		'globalThis.__SYSTEM_TEMPLATES__': JSON.stringify(systemTemplates),
		// Inject bundled personas into the build
		'globalThis.__SYSTEM_PERSONAS__': JSON.stringify(systemPersonas),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
